--Magnitude Analysis
--Compare the Measure Values by categories
--It helps us understand the importance of different categories

--KEY FORMULA: aggregate measures by Dimension (p.ex: Total Sales by Country, Total Quant. by Category)

--TASK
/* Find Total Customers by Countries
  Find Total Customers by gender
  Find Total products by Category
  What is the Average costs in each category?
  What is the total revenue generated for each category?
  Find Total revenue is generated by each customer
  What is the distribution of sold items across countries?
  */

  SELECT 
 'Total Sales' as measure_name, SUM(sales_amount) [measure_value]
FROM gold.fact_sales
UNION ALL
SELECT 
'Total Quantity' as measure_name, SUM(quantity) [total_itens]
FROM gold.fact_sales
UNION ALL
SELECT 
'Average Price' as measure_name, AVG(price) [average_price]
FROM gold.fact_sales
UNION ALL
SELECT
'Total Nr. Orders' as measure_name, COUNT(DISTINCT order_number) [ ]
FROM gold.fact_sales
UNION ALL
SELECT
'Total Nr. Products' as measure_name,COUNT(product_name) [total_products] 
FROM gold.dim_products
UNION ALL
SELECT
'Total Nr. Customers' as measure_name,COUNT(DISTINCT customer_key) [Customers_orders]
FROM gold.fact_sales

--Find Total Customers by Countries
SELECT 
Country,
COUNT(customer_id) AS [Total Customers]
FROM gold.dim_customers
GROUP BY Country
ORDER BY [Total Customers] desc

-- Find Total Customers by gender
SELECT 
gender,
COUNT(customer_id) AS [Total Customers]
FROM gold.dim_customers
GROUP BY gender
ORDER BY [Total Customers] desc

-- Find Total products by Category
SELECT
category,
COUNT(product_name) [total_products] 
FROM gold.dim_products
GROUP BY category
ORDER BY [total_products] desc

-- What is the Average costs in each category?
SELECT 
category,
AVG(cost) [average_price]
FROM gold.dim_products
GROUP BY category
ORDER BY [average_price] DESC

--What is the total revenue generated for each category?
SELECT
category,
SUM(sales_amount) [Total_revenue]
FROM gold.fact_sales as s
LEFT JOIN gold.dim_products as p
ON ( s.product_key = p.product_key)
GROUP BY category
ORDER BY [Total_revenue] DESC

--What is the total revenue generated for each customer?

SELECT
d.customer_key,
d.first_name,
d.last_name,
SUM(sales_amount) [Total_revenue]
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as d
ON (f.customer_key = d.customer_key)
GROUP BY d.customer_key, d.first_name, d.last_name
ORDER BY [Total_revenue] DESC

--What is the distribution of items sold across countries

SELECT
d.country,
SUM(f.quantity) [total_itens]
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers as d
ON (d.customer_key = f.customer_key)
GROUP BY country
ORDER BY [total_itens] DESC

